apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: non-www-redirect-backend
  labels:
    app: non-www-redirect-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: non-www-redirect-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: non-www-redirect-backend
        image: acoshift/non-www-redirect-backend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: non-www-redirect-backend
  labels:
    app: non-www-redirect-backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: non-www-redirect-backend
